on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'testing github actions'
        run: pwd
      - name: 'print my name'
        run: echo 'hello Seif'